* 3

** 3.2.3

S_0   = \emptyset
S_{i+1} = {true, false, 0}
     \cup {succ t_1, pred t_1, iszero t_1 | t_1 \in S_i}
     \cup {if t_1 then t_2 else t_3 | t_1, t_2, t_3 \in S_i}.

S = \cup S_i.
    i 

** 3.2.4

*** How many elements does S_3 have?

notes:
If you are picking 2, and have 3 choices, it is 3^2.

**** S_0 
Empty, easy to discard

lenght(S_0) = 0

**** S_1
This is the union of the 3 sets defined for S_{i+1}. Because this is the first
induction with the constraint that t_1, t_2, t_3 \in S_0 which is an empty set. This
means only the terms that do not have sub terms can be represented giving:

S_1 = {true, false, 0}

**** S_2 

This is the union of the 3 sets in the second induction. This means that t_1, t_2,
t_3 \in S_1. Because if t_1 then t_2 else t_3 has three values to be injected into
it, denoted by the subscript being different, and there are 3 possible values to
inject because of the length of S_1 above, we get 3^3. Then we know that there are
3 terms {succ t_1, pred t_1, iszero t_1} who all need 1 value each and there 3
values to inject. This gives us 3 \times 3. Finally we have the 3 constants to be put
into the set.

length(S_2) = 3^3 + (3 \times 3) + 3
length(S_2) = 39

**** S_3

If we continue with the logic of S_2, considering that there are 39 terms to
inject from the length of S_2, we can just follow the previous math:

length(S_3) = 39^3 + (3 \times 39) + 3
length(S_3) = 59319 + 117 + 3
length(S_3) = 59439

** 3.2.5

